### ISSUE TITLE
The AUR package doesn't work

### ISSUE THREAD

**Issue by Ved-un** [Luxxgit2k4/pacsaviour#1]
The main.sh specifies relative paths    
```
case $choice in
  1) ./scripts/mirror_optimize.sh
    ;;
  2) ./scripts/cleanup.sh
    ;;
  3) ./scripts/update.sh
    ;;
  4) echo "Exiting..."
    exit 0
    ;;
  *) echo "Invalid option"
    ;;
esac
```
and in PKGBUILD all scripts are in a different location     
```
  install -Dm755 "$srcdir/$pkgname/main.sh" "$pkgdir/usr/bin/pacsaviour"
  install -Dm755 "$srcdir/$pkgname/scripts/mirror_optimize.sh" "$pkgdir/usr/lib/pacsaviour/mirror_optimize.sh"
  install -Dm755 "$srcdir/$pkgname/scripts/cleanup.sh" "$pkgdir/usr/lib/pacsaviour/cleanup.sh"
  install -Dm755 "$srcdir/$pkgname/scripts/update.sh" "$pkgdir/usr/lib/pacsaviour/update.sh"
```

**Comment by Luxxgit2k4** [comment]
Hi @Ved-un 
Thank you for reporting the issue! The reason main.sh initially specified relative paths was because it was used during local development and testing.

Fix:
Updated the main.sh script to determine the correct path for the scripts directory:

./scripts when run locally during development or testing from the cloned repository.
/usr/lib/pacsaviour when installed as an AUR package.

```bash 
if [[ -d "./scripts" ]]; then
    SCRIPT_DIR="./scripts"
else
    SCRIPT_DIR="/usr/lib/pacsaviour"
fi
```

Also verified that the PKGBUILD installs the scripts into /usr/lib/pacsaviour and the main executable (pacsaviour) into /usr/bin, which aligns with the updated main.sh.   I hope this resolves the issue!
